export enum IgnoreReason {
  TESTS_REQUIRE_BUILD_BEFORE_BEING_ANALYZED = 'TESTS_REQUIRE_BUILD_BEFORE_BEING_ANALYZED',
  APPLICATION_REQUIRE_BUILD_BEFORE_BEING_ANALYZED = 'APPLICATION_REQUIRE_BUILD_BEFORE_BEING_ANALYZED',
  USES_JSX = 'USES_JSX',
  TEST_DEPENDENCY_REQUIRES_ANALYSIS_ON_PACKED_CODE = 'TEST_DEPENDENCY_REQUIRES_ANALYSIS_ON_PACKED_CODE',
  NO_JS_TESTS_PRESENT = 'NO_JS_TESTS_PRESENT',
  RECAST_MISSING_SOURCE_LOCATIONS = 'RECAST_MISSING_SOURCE_LOCATIONS',
  API_INFERENCE_RUNS_INFINITELY_SINCE_CALLED_FUNCTION_RUNS_INFINITELY = 'API_INFERENCE_RUNS_INFINITELY_SINCE_CALLED_FUNCTION_RUNS_INFINITELY',
  COULD_NOT_GENERATE_PACKAGE_MODEL_FOR_FILE_SINCE_FILE_FAILS_LOAD = 'COULD_NOT_GENERATE_PACKAGE_MODEL_FOR_FILE_SINCE_FILE_FAILS_LOAD', // The load also fails without running through nodeprof.
}
export interface Client {
  name: string;
  repo: {
    gitURL: string;
    gitCommit: string;
  };
  testDir?: string;
  testFile?: string;
  ignore?: IgnoreReason;
}
